language: node_js
node_js: 6
deploy:
  provider: npm
  email: wmhilton@gmail.com
  on:
    node: node
    tags: true
    branch: master
    repo: wmhilton/beautify
  api_key:
    secure: QZFyIZnfxZNcqW+sx6hiqrIvDetbMyYju3q2qr5wM6IJBVebjleyLO9Bt58ch6K6qfTH0Ew+Spwxkz80CPoAeA7yOc+Y+SPD5XX0c05dCJ4LSBZlQg/5dgmcN9FPOeHfDM8trqExt0zfkvIROa/+jgByt0cnpnaSjL6tPgqQTv9D89KtNWjXiNorTXCwczbJgUF3XPEwlcooUK5eJyrdI40ayFWezTzekfwEtlaFub3R2e630qtM3bUWBfZu/Hz9wz704kdmtghZryvF99e0YqGSKeQcshDxHtZYBQHXOtvrEZW6szfNYPInPqsKqk9Lj/x1esgHYVIRCScohz/l78j5I4GxyCI63Hh7Ml4x7vzO+M8zLxUn6uPEOp2TglTZ0yiCDaJHXRsDf0+9O7xPrsoZv5q+9kq8sKPDspNLN/qJ6havoab7bd2T4/X6mMuMUBMo+jhap7lSrHNNl3ugGl9Iwlo+oW/+obCq2Ndqes2MTcdH3ybNiWe2LY9SenKvOnJsqyJKHLDcFJ+ARbPaeDBmfP0/u6NNzP4BQ9U2Bi5t8Ni5QNFT3+4GNH+EDM/w2xGSYKFCN8aS/oiVV9A5W7x+RStBbqkwgrVPcQ5HnIcd8VGRE2wAz4daobJgyWbThzeyJxh9+5+PMVnIK2wgs3CkLj8qtPDyhTrsdQMZqcw=
