// @flow
export default {
  '!DOCTYPE': {display: 'inline'},
  'a': {display: 'inline'},
  'abbr': {display: 'inline'},
  'acronym': {display: 'inline'},
  'address': {display: 'block'},
  'area': {display: 'inline', void: true},
  'article': {display: 'block'},
  'aside': {display: 'block'},
  'b': {display: 'inline'},
  'base': {display: 'block', void: true},
  'bdo': {display: 'inline'},
  'big': {display: 'inline'},
  'blockquote': {display: 'block'},
  'br': {display: 'block', void: true},
  'button': {display: 'inline'},
  'canvas': {display: 'block'},
  'cite': {display: 'inline'},
  'code': {display: 'inline', whitespace: 'preserve'},
  'col': {display: 'inline', void: true},
  'comment': {display: 'block'},
  'dd': {display: 'block'},
  'dfn': {display: 'inline'},
  'div': {display: 'block'},
  'dl': {display: 'block'},
  'em': {display: 'inline'},
  'embed': {display: 'block', void: true},
  'fieldset': {display: 'block'},
  'figcaption': {display: 'block'},
  'figure': {display: 'block'},
  'footer': {display: 'block'},
  'form': {display: 'block'},
  'h1': {display: 'block'},
  'h2': {display: 'block'},
  'h3': {display: 'block'},
  'h4': {display: 'block'},
  'h5': {display: 'block'},
  'h6': {display: 'block'},
  'header': {display: 'block'},
  'hgroup': {display: 'block'},
  'hr': {display: 'block', void: true},
  'i': {display: 'inline'},
  'img': {display: 'inline', void: true},
  'input': {display: 'block', void: true},
  'kbd': {display: 'inline'},
  'label': {display: 'inline'},
  'li': {display: 'block'},
  'link': {display: 'block', void: true},
  'main': {display: 'block'},
  'map': {display: 'inline'},
  'meta': {display: 'block', void: true},
  'nav': {display: 'block'},
  'noscript': {display: 'block'},
  'object': {display: 'inline'},
  'ol': {display: 'block'},
  'option': {display: 'block'},
  'output': {display: 'block'},
  'p': {display: 'block'},
  'param': {display: 'inline', void: true},
  'pre': {display: 'block', whitespace: 'preserve'},
  'q': {display: 'inline'},
  'samp': {display: 'inline'},
  'script': {display: 'block', whitespace: 'preserve'},
  'section': {display: 'block'},
  'select': {display: 'block'},
  'small': {display: 'inline'},
  'source': {display: 'inline', void: true},
  'span': {display: 'inline'},
  'strong': {display: 'inline'},
  'style': {display: 'block', whitespace: 'preserve'},
  'sub': {display: 'inline'},
  'sup': {display: 'inline'},
  'table': {display: 'block'},
  'textarea': {display: 'inline'},
  'tfoot': {display: 'block'},
  'time': {display: 'inline'},
  'tr': {display: 'block'},
  'track': {display: 'inline', void: true},
  'tt': {display: 'inline'},
  'ul': {display: 'block'},
  'var': {display: 'inline'},
  'video': {display: 'block'},
  'wbr': {display: 'inline', void: true}
}
